/* INSERT INTO
  ENTIDAD(ID, NOMBRE)
VALUES
  (1, 'Uno'),
  (2, 'Dos');*/

INSERT INTO USER_ROLE (ID, NAME) VALUES (1, 'ROLE_ADMIN'), (2, 'ROLE_USER');

 INSERT INTO
  USER_(
  ID,
  FULL_NAME,
  PASSWORD,
  USERNAME,
  USER_ROLE_ID
  ) VALUES (
  1,
  'Maximiliano',
  '$2a$10$U63eeYBEQfuDYacvgt6xMe8JS5vwM6sB9g6TfncEFRNjZhQy5L5LS',
  'maxi',
  1
  );

  INSERT INTO
  USER_(
  ID,
  FULL_NAME,
  PASSWORD,
  USERNAME,
  USER_ROLE_ID
  ) VALUES (
  2,
  'Test',
  '$2a$10$U63eeYBEQfuDYacvgt6xMe8JS5vwM6sB9g6TfncEFRNjZhQy5L5LS',
  'usuario-test',
  1
  );

INSERT INTO CLAIM_TYPE (NAME, LOGISTICS) VALUES ('Producto dañado', false);

INSERT INTO CLAIM_STATUS (ID, NAME) VALUES (0, 'PENDIENTE');
INSERT INTO CLAIM_STATUS (ID, NAME) VALUES (1, 'RESUELTO');
INSERT INTO CLAIM_STATUS (ID, NAME) VALUES (2, 'CANCELADO');

INSERT INTO ORDER_STATUS (ID, NAME) VALUES (1, 'CREADO');
INSERT INTO CLIENT (IDENTIFICATION, EMAIL, FULL_NAME) VALUES ('77777777', 'test@test.com', 'Test Client');
INSERT INTO PRODUCT (ID, DESCRIPTION) VALUES (7777, 'test-product');

INSERT INTO ORDER_ (ID, CLIENT_IDENTIFICATION, ORDER_STATUS_ID, PRODUCT_ID) VALUES (7777, '77777777', 1, 7777);

